---
name: QuestDB
version: dev
url: https://questdb.com/
image: "ghcr.io/stevusprimus-hassio-addons/questdb/{arch}"
panel_icon: mdi:face-recognition
slug: questdb
description: QuestDB is the fastest growing open-source time-series database
arch:
  - amd64
  - aarch64
startup: services
init: false
ingress: true
ingress_port: 9000
ingress_stream: true
privileged:
  - PERFMON
ports:
  9000/tcp:
  8812/tcp: 8812
  9009/tcp: 9009
  9449/tcp: 9449
ports_description:
  9000/tcp: HTTP API (not exposed by default)
  8812/tcp: PostgreSQL wire protocol
  9449/tcp: InfluxDB Line Protocol (SSL)
  9009/tcp: InfluxDB Line Protocol
map:
  - addon_config:rw
  - ssl
  - share:rw
options:
  # auth: true
  # reporting: true
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  envvars: []
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  # auth: bool
  # reporting: bool
  ssl: bool
  certfile: str
  keyfile: str
  envvars:
    - name: match(^QUESTDB_([A-Z0-9_])+$)
      value: str
