name: QuestDB
version: 3deaf75
url: https://questdb.com/
image: ghcr.io/stevusprimus-hassio-addons/questdb/{arch}
panel_icon: mdi:face-recognition
slug: questdb
description: QuestDB is the fastest growing open-source time-series database
arch:
- amd64
- aarch64
startup: services
init: false
ingress: true
ingress_port: 9443
privileged:
- PERFMON
ports:
  9000/tcp: 9000
  8812/tcp: 8812
  9009/tcp: 9009
ports_description:
  9000/tcp: HTTP API
  8812/tcp: InfluxDB Line Protocol
  9009/tcp: PostgreSQL wire protocol
map:
- addon_config:rw
- ssl
options:
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  envvars: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssl: bool
  certfile: str
  keyfile: str
  envvars:
  - name: match(^INFLUXDB_([A-Z0-9_])+$)
    value: str
  leave_front_door_open: bool?
